# Generated by Django 6.1.1 on 2026-09-30 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['id'], 'verbose_name': 'patient', 'verbose_name_plural': 'patients'},
        ),
    ]
